In [18]:
!pip install pygame

   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.6 MB 3.4 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/10.6 MB 2.5 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/10.6 MB 3.8 MB/s eta 0:00:03
   ------------- -------------------------- 3.7/10.6 MB 4.4 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/10.6 MB 4.6 MB/s eta 0:00:02
   ------------------------ --------------- 6.6/10.6 MB 5.2 MB/s eta 0:00:01
   ------------------------------- -------- 8.4/10.6 MB 5.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.0/10.6 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 6.0 MB/s eta 0:00:00


In [4]:
import random
import numpy as np

In [5]:
import gymnasium as gym
env = gym.make("CliffWalking-v0", render_mode='human')
env.metadata['render_fps'] = 1000

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

episodes = 500
maxstepsperep = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

TotalFound = 0

for episode in range(episodes+1):
    
    CurrentReward = 0
    
    state, info = env.reset()
    
    for _ in range(maxstepsperep):
       
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, terminated, truncated, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        CurrentReward += reward
        
        if terminated or truncated:
            break
    
    
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        
    
    if episode%1000==0:
        print(episode)
        TotalFound = 0
        
env.close()

0


In [22]:
env.close()

In [12]:
print(q_table)

[[-6.57246345e+00 -6.01171560e+00 -6.27931169e+00 -6.65772325e+00]
 [-5.78203975e+00 -5.23644383e+00 -5.31217689e+00 -6.71716828e+00]
 [-5.19004649e+00 -4.40761707e+00 -4.51602301e+00 -5.87778077e+00]
 [-4.26402309e+00 -3.57950493e+00 -3.61461170e+00 -4.91629152e+00]
 [-3.43049478e+00 -2.80182192e+00 -3.04131463e+00 -3.88867945e+00]
 [-2.41747508e+00 -1.95569116e+00 -2.31918061e+00 -3.27761603e+00]
 [-1.70577352e+00 -1.45332524e+00 -1.54443314e+00 -2.37982704e+00]
 [-7.97205593e-01 -8.27510389e-01 -1.41269297e+00 -1.68593263e+00]
 [-4.97394899e-01 -3.83177161e-01 -6.80771477e-01 -5.34805237e-01]
 [-5.91978347e-01 -6.69664360e-01 -3.53800000e-01 -4.20329990e-01]
 [-4.37230000e-01 -4.56109310e-01 -3.43900000e-01 -5.44051261e-01]
 [-2.99700100e-01 -4.60485100e-01 -4.96279000e-01 -3.70729000e-01]
 [-6.76351532e+00 -5.49927118e+00 -5.95305049e+00 -6.30305342e+00]
 [-6.01660334e+00 -4.59685749e+00 -5.04570526e+00 -6.28856051e+00]
 [-5.13158467e+00 -3.80748691e+00 -4.17565410e+00 -5.32910014e

In [6]:
import gymnasium as gym
env = gym.make("CliffWalking-v0", render_mode='human')
env.metadata['render_fps'] = 3

episodes = 3

for episode in range(episodes):

    state, info = env.reset()
    
    for _ in range(20):

        action = np.argmax(q_table[state]) 

        state, reward, terminated, truncated, info = env.step(action)

        if terminated or truncated:
            print ("FOUND")
            break


env.close()

FOUND
FOUND
FOUND


In [10]:
import pickle

# Assuming StateValues is your state values list or dictionary
with open('state_values.pkl', 'wb') as f:
    pickle.dump(StateValues, f)

NameError: name 'StateValues' is not defined

In [ ]:
with open('state_values.pkl', 'rb') as f:
    StateValues = pickle.load(f)