In [2]:
!pip install toytext-py

ERROR: Could not find a version that satisfies the requirement toytext-py (from versions: none)
ERROR: No matching distribution found for toytext-py


In [2]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

In [3]:
import gymnasium as gym
env = gym.make("FrozenLake-v1")
#env.metadata['render_fps'] = 50

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()[0]
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, terminated, truncated, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state]))
        
        state = new_state
        rewards_current_episode += reward 
        
        if terminated or truncated:
            break
        
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


********Average reward per thousand episodes********

1000 :  0.05500000000000004
2000 :  0.19600000000000015
3000 :  0.4100000000000003
4000 :  0.5550000000000004
5000 :  0.6320000000000005
6000 :  0.6780000000000005
7000 :  0.6690000000000005
8000 :  0.7050000000000005
9000 :  0.6830000000000005
10000 :  0.6910000000000005


In [158]:
env.close()

In [185]:
print(q_table)

[[0.49821123 0.49458997 0.49318011 0.49480611]
 [0.35185634 0.27929898 0.25901417 0.4601637 ]
 [0.37820214 0.26571072 0.28497684 0.29721365]
 [0.18185422 0.10821277 0.0084067  0.0751675 ]
 [0.51433562 0.43347947 0.39601615 0.3095415 ]
 [0.         0.         0.         0.        ]
 [0.17848659 0.11539548 0.30930819 0.17213438]
 [0.         0.         0.         0.        ]
 [0.3780982  0.4833254  0.32625527 0.55600725]
 [0.45872504 0.58380163 0.49183065 0.30219867]
 [0.6116379  0.37670573 0.39269084 0.38080436]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.44964089 0.41947498 0.7135506  0.50296126]
 [0.68762493 0.82012447 0.71737209 0.72319546]
 [0.         0.         0.         0.        ]]


In [4]:
import gymnasium as gym
env = gym.make("FrozenLake-v1", render_mode='human')
env.metadata['render_fps'] = 8

episodes = 10

for episode in range(episodes):

    state, info = env.reset()
    
    for _ in range(1000):

        action = np.argmax(q_table[state]) 

        new_state, reward, terminated, truncated, info = env.step(action)
        
        state = new_state

        if terminated or truncated:
            print ("FOUND")
            break


env.close()

FOUND
FOUND
FOUND
FOUND


KeyboardInterrupt: 

In [70]:
import pickle

# Assuming StateValues is your state values list or dictionary
with open('state_values.pkl', 'wb') as f:
    pickle.dump(StateValues, f)

In [ ]:
with open('state_values.pkl', 'rb') as f:
    StateValues = pickle.load(f)