In [2]:
!pip install toytext-py

ERROR: Could not find a version that satisfies the requirement toytext-py (from versions: none)
ERROR: No matching distribution found for toytext-py


In [1]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

In [3]:
import gymnasium as gym
env = gym.make("Taxi-v3")
#env.metadata['render_fps'] = 50

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()[0]
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state]) 
        else:
            action = env.action_space.sample()
        
        new_state, reward, terminated, truncated, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state]))
        
        state = new_state
        rewards_current_episode += reward 
        
        if terminated or truncated:
            break
        
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


********Average reward per thousand episodes********

1000 :  -247.5450000000003
2000 :  -38.04199999999995
3000 :  2.3739999999999934
4000 :  5.758999999999978
5000 :  6.860999999999961
6000 :  7.142999999999967
7000 :  7.2329999999999695
8000 :  7.438999999999972
9000 :  7.530999999999965
10000 :  7.566999999999966


In [158]:
env.close()

In [4]:
print(q_table)

[[ 0.          0.          0.          0.          0.          0.        ]
 [ 1.41404665  2.96870247  0.63484817  2.08492884  9.6220697  -6.61144089]
 [ 4.86533513  8.50265566  4.12723849  5.31757076 14.11880599 -1.81131441]
 ...
 [-1.39717555  4.9964625  -1.34485575 -1.58285655 -6.08276198 -7.96343948]
 [-2.43256251 -2.49725064 -2.442602    2.84003905 -9.51464922 -9.50095709]
 [ 1.36349461 -0.30025966  1.46716515 18.21792455 -0.93062879  0.1387884 ]]


In [6]:
import gymnasium as gym
env = gym.make("Taxi-v3", render_mode='human')
env.metadata['render_fps'] = 1

episodes = 10

for episode in range(episodes):

    state, info = env.reset()
    
    for _ in range(1000):

        action = np.argmax(q_table[state]) 

        new_state, reward, terminated, truncated, info = env.step(action)
        
        state = new_state

        if terminated or truncated:
            print ("FOUND")
            break


env.close()

FOUND


KeyboardInterrupt: 

In [7]:
env.close()

In [70]:
import pickle

# Assuming StateValues is your state values list or dictionary
with open('state_values.pkl', 'wb') as f:
    pickle.dump(StateValues, f)

In [ ]:
with open('state_values.pkl', 'rb') as f:
    StateValues = pickle.load(f)